import React, { useState } from 'react';
import { 
  Presentation, 
  ChevronLeft, 
  ChevronRight, 
  Maximize2, 
  Sparkles, 
  ShieldAlert, 
  CheckCircle2, 
  TrendingUp, 
  DollarSign, 
  Building2, 
  Network, 
  Layers, 
  Download,
  Users,
  Award
} from 'lucide-react';

interface Slide {
  number: number;
  title: string;
  category: string;
  headline: string;
  bullets: string[];
  callout?: string;
  metric?: { label: string; value: string };
}

const SLIDES: Slide[] = [
  {
    number: 1,
    title: 'FranchiseGuard AI',
    category: 'Title Slide',
    headline: 'Continuous AI-Powered Franchise Compliance & Risk-Monitoring Platform',
    bullets: [
      'Problem Statement: Franchise Standards Auditor',
      'Turning scattered franchise data into continuous AI compliance monitoring',
      'Presenter: FranchiseGuard AI Team',
      'Target: Multi-Unit Franchise Headquarters & Brand Operations',
    ],
    callout: 'Executive Pitch Deck — Submission 2026',
  },
  {
    number: 2,
    title: 'Executive Summary',
    category: 'Overview',
    headline: 'Replacing Occasional Physical Inspections with 24/7 Multi-Modal AI Monitoring',
    bullets: [
      'Franchise brands manage 100 to 5,000+ locations with limited physical inspection capacity.',
      'Headquarters receives massive, disconnected streams: photos, customer reviews, POS records, and audit notes.',
      'FranchiseGuard AI correlates all data streams, calculates a real-time Risk Score (0-100), and flags systemic defects.',
      'Humans-in-the-loop retain authority while operational audit costs drop by 60%.',
    ],
    metric: { label: 'Audit Cost Reduction', value: '60%' },
  },
  {
    number: 3,
    title: 'The Core Problem: The Franchise Oversight Gap',
    category: 'Problem',
    headline: 'Brands Blind Between Infrequent On-Site Audits',
    bullets: [
      'Physical audits occur only 1 to 4 times per year due to travel costs and inspector shortages.',
      'Locations frequently "stage" compliance for scheduled inspections, then standards degrade.',
      'A single substandard location damages brand equity across the entire national fleet.',
      'By the time customer complaints trigger a manual audit, revenue and customer retention have collapsed.',
    ],
    metric: { label: 'Time Unmonitored / Year', value: '92%' },
  },
  {
    number: 4,
    title: 'Current Industry Pain Points',
    category: 'Problem Analysis',
    headline: 'Disconnected Data Silos at Headquarters',
    bullets: [
      'Silo 1: Inspection reports locked in static PDF attachments.',
      'Silo 2: Public review sites (Google, Yelp) disconnected from field operations.',
      'Silo 3: Store photos submitted on WhatsApp or email without automated verification.',
      'Silo 4: Point-of-Sale anomalies (revenue drop, ticket delays) investigated too late.',
    ],
  },
  {
    number: 5,
    title: 'Market Opportunity: The $860B Franchise Economy',
    category: 'Market',
    headline: 'Massive TAM in QSR, Hospitality, Retail, and Fitness',
    bullets: [
      '800,000+ franchise establishments in North America alone.',
      '$860B+ economic output generated by multi-unit franchise systems.',
      'Average brand spends $2,400 to $4,800 per location per year on manual audits and travel.',
      'Total Addressable Software Market (TAM): $4.2 Billion annually.',
    ],
    metric: { label: 'North American Stores', value: '800k+' },
  },
  {
    number: 6,
    title: 'The Solution: FranchiseGuard AI',
    category: 'Solution',
    headline: 'Continuous AI Compliance Command Center',
    bullets: [
      'Automated Computer Vision auditing of photos and CCTV frames against SOP manuals.',
      'NLP sentiment analysis identifying recurring cleanliness and food safety complaints.',
      'Algorithmic Risk Scoring Engine synthesizing 5 weighted operational dimensions.',
      'Human-in-the-loop governance for legal cure notices and inspection dispatch.',
    ],
  },
  {
    number: 7,
    title: 'Core Value Proposition',
    category: 'Value',
    headline: 'Inspect by Exception, Not by Random Chance',
    bullets: [
      'HQ only sends auditors to the top 5% highest-risk locations.',
      'Early detection prevents health department shutdowns and negative viral PR.',
      'Objective, data-backed evidence simplifies franchisee dispute resolution.',
      'Systemic equipment and supply chain defects caught across hundreds of stores.',
    ],
    metric: { label: 'Brand Risk Reduction', value: '78%' },
  },
  {
    number: 8,
    title: 'Multi-Source Data Ingestion Architecture',
    category: 'Architecture',
    headline: 'Unifying 6 Distinct Franchise Signal Streams',
    bullets: [
      'Stream 1: Daily closing and prep photos uploaded via mobile auditor web app.',
      'Stream 2: Public Google, Yelp, and DoorDash review streams via NLP webhooks.',
      'Stream 3: Historical audit archives and unresolved corrective action plans.',
      'Stream 4: POS transaction velocity, ticket preparation times, and revenue trends.',
    ],
  },
  {
    number: 9,
    title: 'Multimodal AI Vision & NLP Pipeline',
    category: 'Technology',
    headline: 'Powered by Gemini 3.7 Vision & Multimodal Reasoning',
    bullets: [
      'Computer Vision identifies tile grease, uniform lapses, signage outages with 94%+ confidence.',
      'Extracts spatial bounding boxes for visual verification and franchisee clarity.',
      'Natural Language Processing categorizes unstructured customer complaints into 6 SOP domains.',
      'Correlates photo evidence with customer review spikes for undeniable proof.',
    ],
  },
  {
    number: 10,
    title: 'The Risk Scoring Formula',
    category: 'Scoring Engine',
    headline: 'Mathematical, Transparent Composite Scoring (0-100)',
    bullets: [
      'Photo Violations: +10 to +30 points (based on severity and confidence).',
      'Customer Complaints: +5 to +20 points (sentiment score and volume).',
      'Historical Recurrence: +15 to +30 points (repeated failures across 2+ audits).',
      'Business Signals: +5 to +15 points (abnormal revenue drops or ticket delays).',
      'Unresolved Actions: +10 to +25 points (overdue corrective plans > 30 days).',
    ],
    callout: 'Tiers: Low (0-29) • Medium (30-59) • High (60-89) • Critical (90-100)',
  },
  {
    number: 11,
    title: 'Explainable AI & Synthesis Engine',
    category: 'AI Synthesis',
    headline: 'No Black-Box Scores: Plain-English Executive Rationales',
    bullets: [
      'AI synthesizes an executive summary explaining why a location scored high risk.',
      'Quotes specific standard clause violations from the brand SOP manual.',
      'Recommends concrete, actionable operational directives for field staff.',
      'Generates legally compliant 14-day cure notice documents in one click.',
    ],
  },
  {
    number: 12,
    title: 'Human-in-the-Loop Governance',
    category: 'Governance',
    headline: 'AI Recommends — Human Managers Decide',
    bullets: [
      'AI does NOT unilaterally issue legal penalties or schedule surprise audits.',
      'Franchise Compliance Managers review evidence in a dedicated approval queue.',
      'One-click approval dispatches auditors or files certified cure notices.',
      'Every manager action and note is logged in a tamper-proof audit trail.',
    ],
    metric: { label: 'Human Governance', value: '100%' },
  },
  {
    number: 13,
    title: 'Cross-Location Pattern Detection: The Killer Feature',
    category: 'Differentiation',
    headline: 'Identifying Fleet-Wide Supplier & Vendor Deficiencies',
    bullets: [
      'Compares compliance signals across all 500 locations simultaneously.',
      'Discovers systemic trends (e.g. 14 stores with TrueCold cooler gasket failures).',
      'Distinguishes isolated store manager negligence from nationwide vendor defects.',
      'Saves brands hundreds of thousands in food spoilage and warranty recovery.',
    ],
    metric: { label: 'Fleet Savings (Case)', value: '$180,000' },
  },
  {
    number: 14,
    title: 'Automated Remediation & Cure Notice Engine',
    category: 'Workflow',
    headline: 'From Detection to Legal Compliance Notice in 60 Seconds',
    bullets: [
      'Automates generation of certified 14-Day Notice to Cure Default.',
      'Attaches exact photo timestamps, clause citations, and inspection failure history.',
      'Integrates electronic signature and certified delivery tracking.',
      'Reduces legal drafting overhead by 90%.',
    ],
  },
  {
    number: 15,
    title: 'The Store #247 Live Case Study',
    category: 'Validation',
    headline: 'End-to-End Walkthrough of a High-Risk Intervention',
    bullets: [
      'Photo upload detected tile floor grease (94.2%) and missing hairnet (91.8%).',
      'NLP review stream caught 7 customer complaints citing sticky floors.',
      'Recurrence engine correlated 3 consecutive audit failures and 86-day overdue action.',
      'Calculated Risk Score: 91/100 (Critical). Manager approved physical inspection in 1 click.',
    ],
  },
  {
    number: 16,
    title: 'Business Model & Unit Economics',
    category: 'Business Model',
    headline: 'B2B SaaS Subscription (Per-Location / Month)',
    bullets: [
      'Starter Tier: $149 / location / month (Core vision & review monitoring).',
      'Enterprise Tier: $249 / location / month (Full cross-location analytics & legal cure notices).',
      'Typical 500-store brand = $1.5M Annual Recurring Revenue (ARR).',
      'Gross margins exceeding 82% on cloud container infrastructure.',
    ],
    metric: { label: 'ARR (500 Stores)', value: '$1.5M' },
  },
  {
    number: 17,
    title: 'Total Addressable Market (TAM)',
    category: 'Market Sizing',
    headline: '$4.2B Serviceable Available Market in North America',
    bullets: [
      'TAM: $12.4B Global Franchise Compliance & Auditing Software.',
      'SAM: $4.2B North American QSR, Fast Casual, and Retail Franchise Brands.',
      'SOM: $420M initial focus on brands with 100 to 2,000 locations.',
      'Expansion into fitness (Planet Fitness, Anytime) and hospitality (Marriott, Hilton).',
    ],
    metric: { label: 'SOM Focus', value: '$420M' },
  },
  {
    number: 18,
    title: 'Competitive Advantage & Defensive Moat',
    category: 'Competition',
    headline: 'Why FranchiseGuard AI Outperforms Point Solutions',
    bullets: [
      'Checklist Apps (Zenput, SafetyCulture): Manual, prone to employee cheating.',
      'Reputation Tools (Birdeye, Yext): Review-only, no computer vision or SOP correlation.',
      'Physical Audits: High cost ($1,200/visit), infrequent, snapshot-in-time.',
      'FranchiseGuard AI Moat: Multi-modal fusion + Cross-location systemic correlation.',
    ],
  },
  {
    number: 19,
    title: 'Customer ROI & Financial Impact',
    category: 'ROI',
    headline: '6.4x Return on Investment in Year 1',
    bullets: [
      'Save $280k/yr on unnecessary random field auditor travel.',
      'Prevent $180k/yr in food inventory spoilage via systemic equipment alerts.',
      'Protect brand equity from catastrophic viral PR and health closures.',
      'Average payback period: Under 45 days.',
    ],
    metric: { label: 'Year 1 ROI', value: '6.4x' },
  },
  {
    number: 20,
    title: 'Technical Architecture & Security',
    category: 'Engineering',
    headline: 'Enterprise-Grade Security & Containerized Scalability',
    bullets: [
      'Backend: Node.js / Express with Gemini 3.7 Multimodal SDK.',
      'Frontend: React 19, Vite, Tailwind CSS with Recharts & responsive layout.',
      'Security: SOC2 compliant architecture, encrypted storage, RBAC authentication.',
      'Throughput: 10,000+ photo inferences per minute with sub-second scoring.',
    ],
  },
  {
    number: 21,
    title: 'Ideal Customer Profile (ICP)',
    category: 'Target Market',
    headline: 'Who Buys FranchiseGuard AI?',
    bullets: [
      'VP of Franchise Operations & Chief Compliance Officers.',
      'Franchise brands with 100 to 3,000 locations in rapid geographic expansion.',
      'Multi-Unit Franchisees operating 20+ units needing internal quality control.',
      'Key verticals: Quick-Service Restaurants (QSR), Fitness, Auto Services, Child Care.',
    ],
  },
  {
    number: 22,
    title: 'Go-to-Market (GTM) Strategy',
    category: 'GTM',
    headline: 'Direct Enterprise Sales + IFA Partnership Channel',
    bullets: [
      'Direct Sales: Target Top 200 franchise franchisors via outbound ABM.',
      'IFA (International Franchise Association) event sponsorships & workshops.',
      'Free 30-Day Fleet Compliance Audit (Analyze 50 stores free to prove ROI).',
      'Integration partnerships with Toast, Olo, and Revel POS ecosystems.',
    ],
  },
  {
    number: 23,
    title: 'Product Roadmap: 2026-2027',
    category: 'Roadmap',
    headline: 'From Reactive Audits to Autonomous Compliance Ecosystem',
    bullets: [
      'Q3 2026 (Live Now): Multimodal Vision + NLP + Risk Scoring + Cross-Location.',
      'Q4 2026: Live CCTV RTSP continuous edge-stream ingestion & heatmapping.',
      'Q1 2027: Automated micro-training dispatch for line staff on detected infractions.',
      'Q2 2027: AI Franchise Agreement contract generator & dispute mediation bot.',
    ],
  },
  {
    number: 24,
    title: 'Team & Franchise Advisory',
    category: 'Team',
    headline: 'World-Class AI Engineers & Franchise Operations Veterans',
    bullets: [
      'AI / ML Lead: Former Google DeepMind & Computer Vision Researchers.',
      'Franchise Industry Advisor: 20+ years executive leadership at Tier-1 QSR brand.',
      'Enterprise SaaS Architecture: Scaled platforms serving 50,000+ commercial endpoints.',
      'Legal & Compliance Advisor: Franchise Law & FDD Regulatory Specialist.',
    ],
  },
  {
    number: 25,
    title: 'Vision & The Future of Franchise Brand Protection',
    category: 'Conclusion',
    headline: 'Continuous AI Compliance Is the Future of Franchise Operations',
    bullets: [
      'No brand should discover store degradation through viral TikToks or health shutdowns.',
      'FranchiseGuard AI empowers headquarters and franchisees to build trustworthy brands.',
      'Ready for live enterprise deployment across 500 locations today.',
      'Thank you! Questions & Live Demo.',
    ],
    callout: 'FranchiseGuard AI — Compliance Built for Scale',
  },
];

export const PresentationDeck: React.FC = () => {
  const [currentSlideIndex, setCurrentSlideIndex] = useState<number>(0);
  const currentSlide = SLIDES[currentSlideIndex];

  return (
    <div className="space-y-6 pb-12">
      {/* Top Deck Controls */}
      <div className="bg-white border border-slate-200 p-6 rounded-2xl shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-slate-900 tracking-tight">Executive Presentation Deck (25 Slides)</h1>
            <span className="bg-indigo-50 text-indigo-700 border border-indigo-200 text-xs px-2.5 py-0.5 rounded-full font-bold">
              September 23 Submission Ready
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Comprehensive business, market, technical architecture, and financial pitch for FranchiseGuard AI.
          </p>
        </div>

        {/* Slide Counter & Carousel buttons */}
        <div className="flex items-center gap-3">
          <span className="text-xs font-semibold text-slate-600">
            Slide <strong className="text-slate-900">{currentSlide.number}</strong> of <strong className="text-slate-900">{SLIDES.length}</strong>
          </span>

          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setCurrentSlideIndex((i) => Math.max(0, i - 1))}
              disabled={currentSlideIndex === 0}
              className="p-2 bg-slate-100 hover:bg-slate-200 disabled:opacity-30 rounded-lg border border-slate-200 text-slate-700 transition-colors cursor-pointer"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button
              onClick={() => setCurrentSlideIndex((i) => Math.min(SLIDES.length - 1, i + 1))}
              disabled={currentSlideIndex === SLIDES.length - 1}
              className="p-2 bg-slate-100 hover:bg-slate-200 disabled:opacity-30 rounded-lg border border-slate-200 text-slate-700 transition-colors cursor-pointer"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Main Slide Canvas (16:9 Presentation Aspect Ratio) */}
      <div className="bg-white border border-slate-200 p-8 sm:p-12 rounded-3xl shadow-md min-h-[480px] flex flex-col justify-between relative overflow-hidden">
        {/* Background Watermark / Accent */}
        <div className="absolute right-0 top-0 translate-x-12 -translate-y-12 w-96 h-96 bg-indigo-50/50 rounded-full blur-3xl pointer-events-none" />

        {/* Slide Header */}
        <div className="space-y-2 z-10">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="bg-indigo-600 text-white font-mono text-[11px] font-bold px-2.5 py-0.5 rounded">
                SLIDE {currentSlide.number.toString().padStart(2, '0')}
              </span>
              <span className="text-xs uppercase font-extrabold tracking-wider text-indigo-700">
                {currentSlide.category}
              </span>
            </div>
            <span className="text-xs text-slate-400 font-semibold">FranchiseGuard AI Pitch Deck</span>
          </div>

          <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight leading-tight">
            {currentSlide.title}
          </h2>
          <p className="text-base font-bold text-indigo-700 mt-1">
            {currentSlide.headline}
          </p>
        </div>

        {/* Slide Body Bullets & Metrics */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 my-6 z-10 items-center">
          <div className="lg:col-span-8 space-y-3.5">
            {currentSlide.bullets.map((bullet, idx) => (
              <div key={idx} className="flex items-start gap-3">
                <div className="w-2 h-2 rounded-full bg-indigo-600 mt-2 shrink-0" />
                <p className="text-sm sm:text-base text-slate-700 leading-relaxed font-normal">{bullet}</p>
              </div>
            ))}
          </div>

          {/* Metric or Callout Box */}
          {(currentSlide.metric || currentSlide.callout) && (
            <div className="lg:col-span-4 flex flex-col justify-center">
              {currentSlide.metric && (
                <div className="p-6 bg-indigo-50/60 border border-indigo-200 rounded-2xl text-center space-y-1 shadow-xs">
                  <span className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">{currentSlide.metric.value}</span>
                  <div className="text-xs font-bold uppercase text-indigo-700">{currentSlide.metric.label}</div>
                </div>
              )}

              {currentSlide.callout && (
                <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl text-center text-xs font-bold text-slate-800 mt-3 shadow-xs">
                  {currentSlide.callout}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Slide Footer */}
        <div className="pt-4 border-t border-slate-200 flex items-center justify-between text-xs text-slate-400 z-10">
          <span>Franchise Standards Auditor • AI SaaS B2B</span>
          <span>Confidential — For Review Only</span>
        </div>
      </div>

      {/* Slide Thumbnails Jump Bar */}
      <div className="bg-white border border-slate-200 p-4 rounded-2xl space-y-2 shadow-sm">
        <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Slide Navigator (Jump to any slide)</span>
        <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-thin">
          {SLIDES.map((s, idx) => (
            <button
              key={s.number}
              onClick={() => setCurrentSlideIndex(idx)}
              className={`px-3 py-1.5 rounded-lg border text-xs font-bold whitespace-nowrap transition-all cursor-pointer ${
                currentSlideIndex === idx
                  ? 'bg-indigo-600 border-indigo-600 text-white shadow-xs'
                  : 'bg-slate-50 border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-slate-100'
              }`}
            >
              {s.number}. {s.title}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};
